on:
  push:
    branches:
      - main
    paths:
      - 'force-app/**'
  workflow_dispatch:

jobs:
  deploy-to-sffnoobs-environment:
    runs-on: ubuntu-latest
    environment: sffnoobs

    steps:
      # 1️⃣ Checkout source code
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3️⃣ Install Salesforce CLI
      - name: Install Salesforce CLI
        run: npm install --global @salesforce/cli

      # 4️⃣ Install sfdx-git-delta plugin
      - name: Install sfdx-git-delta
        run: |
          echo y | sf plugins install sfdx-git-delta
          sf plugins

      # 5️⃣ Create delta package
      - name: Create delta packages
        run: |
          mkdir -p changed-sources
          sf sgd source delta \
            --to HEAD \
            --from HEAD^ \
            --output changed-sources \
            --generate-delta \
            --source force-app
          echo "[INFO] Delta generated"

      # 6️⃣ Authenticate to Salesforce using JWT
      - name: Authenticate to Salesforce
        run: |
          printf "%s" "${{ secrets.JWT_SERVER_KEY }}" > server.key
          sf org login jwt \
            --username ${{ secrets.DEPLOYMENT_USER_NAME }} \
            --jwt-key-file server.key \
            --client-id ${{ secrets.CONSUMER_KEY }} \
            --instance-url ${{ vars.INSTANCE_URL }} \
            --set-default

      # 7️⃣ Deploy delta with tests
      - name: Deploy to Salesforce
        run: |
          sf project deploy start \
            --source-dir changed-sources/force-app \
            --test-level RunLocalTests
